# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6391ba9a91898fc3092d31152f0417b21a51e6bf0d765cb8c25fcad31d8b5cd8cc388c4a616f58b393d0aa1f2c246f7249b59d76992ef6170064b206ac236542

test:
  secret_key_base: ac3b64340e0b239399e36fea472177a0f5f5a7f8cbea020b0f1c8d548601cebdce58f350092eebb4a768d85f179580cb917e9df6507a197ec4266011d89c1a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
